feat: implement static blocks
DevExpress/esotope-hammerhead pull request #24
Opened 2023-08-29 11:25 UTC by sorin-davidoi

TestCafe fails to process bundles that contain static initialization blocks.

Example of problematic AST:

```
Node {
  type: 'StaticBlock',
  start: 220015,
  end: 220104,
  body: [
    Node {
      type: 'ExpressionStatement',
      start: 220022,
      end: 220103,
      expression: [Node]
    }
  ]
}
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Static_initialization_blocks

2023-08-30 06:52 UTC, Aleksey28 requested changes
Hi @sorin-davidoi,

Thank you for your contribution. We appreciate your help. Please check my comment and put a custom build with this fix in [your PR in `testcafe-hammerhead`](%5Bhttps://github.com/DevExpress/testcafe-hammerhead/pull/2959%5D(https://github.com/DevExpress/testcafe-hammerhead/pull/2959)).

2023-08-30 06:52 UTC, Aleksey28 commented on esotope.js
> +        for(var i = 0; i < bodyCount; ++i) {
```suggestion
        for (var i = 0; i < bodyCount; ++i) {
```

2023-08-31 07:46 UTC, Aleksey28 requested changes
Your test in testcafe-hammerhead fails in safari. Please fix it.

![0071screenshot](https://github.com/DevExpress/esotope-hammerhead/assets/32869530/bf97dcca-0c7a-404a-a7fc-45603711e981)

2023-08-31 07:53 UTC, sorin-davidoi commented
@Aleksey28  I don't have access to Safari, it passes in a WebKit browser on Linux. The previous tests I've added [were later skipped on iOS](https://github.com/DevExpress/testcafe-hammerhead/pull/2886/commits/1d1a04a77a212f995aff238127f4330bf312ca87), is that reasonable to do here as well?

2023-09-01 07:50 UTC, Aleksey28 commented
I found that Safari supports this feature only in v16.4 and later. Please add this condition before the test:
```js
!browserUtils.isSafari || browserUtils.version >= 16.4
```

2023-09-01 09:41 UTC, Aleksey28 approved these changes
Great!

2023-09-01 09:42 UTC, merged