fix: fixed a case for accesing a private field
DevExpress/esotope-hammerhead pull request #29
Opened 2023-12-18 14:20 UTC by Bayheck

fixed a case for accesing a private field

2023-12-20 08:26 UTC, Aleksey28 requested changes
That's great that you found out the root of the issue. I left some comments about the code style

2023-12-20 08:26 UTC, Aleksey28 commented on esotope.js
> +            const propName     = $prop.type === Syntax.PrivateIdentifier ? "#" + $prop.name : $prop.name;
It's preferable to use single quotes for strings

2023-12-20 08:26 UTC, Aleksey28 commented on esotope.js
> +            const exprChaining = $expr.optional ? '?.' : '.';
There are a few problems with the name `exprChaining`:
1. For what word is the `expr` short form, `express` or `expression`? If the first one it means that it's verb and name `exprChaining` should be used for method or function. Try not to reduce names without reason and if it's not a common name
2. Try to look at the name `exprChaining` without context and answer the question `What does it contain?`. My first thought was that it was an expression sequence connected in one chain, but it's not.
My suggestion for the name of this variable is `chainOperator`

2023-12-21 06:30 UTC, AlexKamaev requested changes

2023-12-21 06:30 UTC, AlexKamaev commented on esotope.js
> +            const propName      = $prop.type === Syntax.PrivateIdentifier ? '#' + $prop.name : $prop.name;
there is very insignificant code duplication with $prop.name and $prop.name.
I would rewrite it as:
```JS
const prefix = $prop.type === Syntax.PrivateIdentifier ? '#' : '';

const propName = $prefix + $prop.name;
```

2023-12-21 07:59 UTC, Aleksey28 approved these changes

2023-12-21 08:43 UTC, AlexKamaev approved these changes

2023-12-22 07:23 UTC, merged